# GitHub Code Validation action for GroupNexus Front-End
# Author: Avinash

name: code_checker

on: [push, pull_request]

jobs:
  testcases:
    name: Validate Code
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setting up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"

      - name: Installing
        run: npm install --silent

      - name: Checking Lint Error
        run: ./node_modules/.bin/eslint --ext .ts,.tsx . || exit 0
